- name: "Installation de haproxy et de keepalived"
  yum:  
    name: "{{ item }}"
    state: present
  with_items:
    - haproxy
    - keepalived
    - psmisc
  register: ha_installed

- name: "Relachement des autorisations SELinux pour haproxy"
  command: /usr/sbin/setsebool -P haproxy_connect_any=1
  when: ha_installed | changed