- name: "Ajout du JAVA_HOME java dans /etc/profile"
  lineinfile:
    dest: /etc/profile
    state: present
    owner: root
    group: root
    regexp: "export JAVA_HOME={{java_jdk_location}}/{{java_jdk_informations[java_jdk_version].output_dir}}/"
    insertafter: EOF
    line: "export JAVA_HOME={{java_jdk_location}}/{{java_jdk_informations[java_jdk_version].output_dir}}/"


- name: "Ajout du PATH java dans /etc/profile"
  lineinfile:
    dest: /etc/profile
    state: present 
    owner: root
    group: root
    regexp: "export PATH=\\$PATH:{{java_jdk_location}}/{{java_jdk_informations[java_jdk_version].output_dir}}/bin/"
    insertafter: EOF
    line: "export PATH=$PATH:{{java_jdk_location}}/{{java_jdk_informations[java_jdk_version].output_dir}}/bin/"

- name: "Creation des liens symboliques dans /usr/bin/"
  file:
    src: "{{java_jdk_location}}/{{java_jdk_informations[java_jdk_version].output_dir}}/bin/{{item}}"
    dest: /usr/bin/java
    owner: root 
    group: root 
    state: link
  with_items:
    - java