== Description ==

Ce repo propose :

* un ensemble de roles ansible
* un ensemble d'infrastructures permettant de tester les roles, ces infrastructures sont basées sur Vagrant.

Exemple de creation d'une infrastructure de servers ubuntu, avec deux haproxy en haute disponibilité 
avec keepalived (les prérequis sont supposés remplis).

[source,bash]
----
$ git clone https://github.com/manueldeval/vagrant-ansible.git
$ cd vagrant-ansible
$ export box_type=ubuntu/vivid64
$ export playbook_path=infrastructures/haproxy_simple
$ vagrant up
----

Exemple de passage des tests unitaires de l'infrastructure créée :

[source,bash]
----
$ ./python/testinfra.sh
----

Cette commande exécute le fichier de test présent dans : `./infrastructures/haproxy_simple/pytest/test.py`.

[source,python]
----
from InfraUnit import infra
import time 

def test_vip_is_on_lb1(infra):
	vipOnLb1 = infra.server('lb1').ssh('ip addr show').stdoutContains("192.168.33.201")
	assert  vipOnLb1 == True

def test_if_haproxy_is_stopped_on_lb1_it_will_be_affected_on_lb2(infra):
	stopHaOnLb1 = infra.server('lb1').ssh('service haproxy stop')
	time.sleep(5)
	vipOnLb2 = infra.server('lb2').ssh('ip addr show').stdoutContains("192.168.33.201")
	assert  vipOnLb2 == True

def test_if_haproxy_is_restarted_on_lb1_it_will_be_affected_on_lb1(infra):
	stopHaOnLb1 = infra.server('lb1').ssh('service  haproxy start')
	time.sleep(5)
	vipOnLb1 = infra.server('lb1').ssh('ip addr show').stdoutContains("192.168.33.201")
	assert  vipOnLb1 == True
----

Suppression d'une infrastructure:

[source,bash]
----
$ vagrant destroy --force
----


== Installation ==

Les prérequis sont les suivants :

* Ansible
* Vagrant
* pytest

=== Ansible ===

*Ubuntu*

[source,bash]
----
$ sudo apt-add-repository ppa:ansible/ansible -y
$ sudo apt-get install software-properties-common
$ sudo apt-get update
$ sudo apt-get install ansible
----

*Centos*

Via EPEL.

[source,bash]
----
$ sudo yum install epel-release
$ sudo yum install ansible
----

=== Vagrant ===

*Ubuntu*

[source,bash]
----
$ sudo apt-get install virtualbox
$ sudo apt-get install vagrant
----

=== pytest ===

[source,bash]
----
$ pip install -U pytest
----

=== Ensemble de box ===

Il est recommandé de préinstaller un ensemble de "box vagrant".

[source,bash]
----
$ vagrant add debian/jessie64
$ vagrant add centos/7
$ vagrant add ubuntu/vivid64
----

== Infrastructures ==

=== haproxy_simple ===

Load balancer en haute dispo.

----
                  *----- lb1: HAPROXY (192.168.33.10)
                  |           Keepalived
                  |                |
    ----- VIP ----*                |
  192.168.33.201  |                |
                  |           Keepalived
                  *----- lb2: Haproxy (192.168.33.11)
----

=== sample_http_service ===

Simple service Json, à des fins de test.

----
    ------ service1: sample_http_service (192.168.33.10)
----
