ha_retries: 3
ha_timeout_connect: 5000
ha_timeout_client: 10000
ha_timeout_server: 10000

ha_www_frontends:
  - name: www
    mode: http
    listen_ip: "0.0.0.0"
    listen_port: 80
    stats_status: enable
    stats_realm: LB_REALM
    stats_admin: admin
    stats_password: password
    stats_uri: /stats
    backends:
      - name: webapp1
        httpchk: HEAD / HTTP/1.1\r\nHost:localhost
        uri_starts: "/webapp1"
        domain_starts: "app1"
        cookie: SERVERID insert indirect nocache
        servers:
          - name: local1
            host: 127.0.0.1
            port: 80
          - host: localhost
            port: 80
            backup: true
      - name: webapp2
        domain_starts: "app2"
        cookie: SERVERID insert indirect nocache
        group:
          name: lb
          port: 80
          eth: eth1
      - name: webapp3
        domain_starts: "app3"
        httpchk: HEAD / HTTP/1.1\r\nHost:localhost
        group:
          nbr_masters: 0
          name: lb
          port: 80
          eth: eth0









